

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainBackgroundPanel;
                ref class TextBlock;
                ref class Button;
                ref class TextBox;
            }
        }
    }
}

namespace RGBClustering
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ SwapChainPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TitleTextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LearningRateTextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LearningRadiusTextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IterationTimesTextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ErrorTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ StartButton;
        private: ::Windows::UI::Xaml::Controls::Button^ StopButton;
        private: ::Windows::UI::Xaml::Controls::Button^ ResetButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ InitialLearningRadiusTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ InitialLearningRateTextBox;
    };
}

